# Generated by Django 3.2.9 on 2023-04-10 09:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20230410_0907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': '4. Categories for notes'},
        ),
        migrations.AlterModelOptions(
            name='checkingtask',
            options={'verbose_name': 'Checking task', 'verbose_name_plural': '1. Checking tasks'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Background images', 'verbose_name_plural': '3. Background images for a note'},
        ),
        migrations.AlterModelOptions(
            name='maptask',
            options={'verbose_name': 'Map task', 'verbose_name_plural': '6. Map tasks'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Note', 'verbose_name_plural': '2. Notes'},
        ),
        migrations.AlterModelOptions(
            name='submaptask',
            options={'verbose_name': 'Sub map task', 'verbose_name_plural': '7. Sub map tasks'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Content task', 'verbose_name_plural': '5. Content tasks'},
        ),
        migrations.AlterField(
            model_name='checkingtask',
            name='finish_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 11, 9, 15, 10, 119001, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maptask',
            name='finish_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 11, 9, 15, 10, 124032, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='submaptask',
            name='finish_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 11, 9, 15, 10, 125133, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='finish_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 11, 9, 15, 10, 122335, tzinfo=utc)),
        ),
    ]
